# Generated by Django 6.0.5 on 2026-06-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_engineer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(max_length=20, unique=True)),
                ('part_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('Hydraulic', 'Hydraulic'), ('Pneumatic', 'Pneumatic'), ('Consumable', 'Consumable')], max_length=30)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('minimum_stock', models.PositiveIntegerField(default=5)),
                ('unit', models.CharField(default='Nos', max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
